language: go

go:
  - "1.10"

before_install:
  - go get -u golang.org/x/lint/golint
  - echo $PATH
  - find $GOPATH/bin

script:
  - go test -v ./...
  - go fmt ./... | grep . && echo "go fmt failed" && exit 1
  - go vet ./...
  - golint -set_exit_status ./...
